### ISSUE TITLE
Can't load markers in Mendix 8.11

### ISSUE THREAD

**Issue by MarkMellink** [ivosturm/GoogleMapsCustomMarker#21] opened 2020-08-15 15:09 UTC
Hi,

I can't load markers using Mendix 8.11. I get the following error message in the console:

`obj.get is not a function TypeError: obj.get is not a function
    at S.<computed>.E.<anonymous> (http://localhost:8080/widgets/GoogleMapsCustomMarker/widget/GoogleMapsCustomMarker.js?637331078010923573:502:100)
    at http://localhost:8080/mxclientsystem/mxui/mxui.js?637331078010923573:5:27280
    at Object.forEach (http://localhost:8080/mxclientsystem/mxui/mxui.js?637331078010923573:5:31063)
    at S.<computed>.E._refreshMap (http://localhost:8080/widgets/GoogleMapsCustomMarker/widget/GoogleMapsCustomMarker.js?637331078010923573:480:23)
    at S.<computed>.E.parseObjects (http://localhost:8080/widgets/GoogleMapsCustomMarker/widget/GoogleMapsCustomMarker.js?637331078010923573:684:9)
    at S.<computed>.E.<anonymous> (http://localhost:8080/widgets/GoogleMapsCustomMarker/widget/GoogleMapsCustomMarker.js?637331078010923573:584:12)
    at S.<computed>.E.<anonymous> (http://localhost:8080/mxclientsystem/mxui/mxui.js?637331078010923573:5:27280)
    at http://localhost:8080/mxclientsystem/mxui/mxui.js?637331078010923573:80:8288`

**Comment by ivosturm** [comment] 2020-08-15 16:07
Hi Mark,

Could you share a bit more of your scenario or even a test project? It helps me to know if you load over XPath/Association/Microflow for instance.

Printscreens of your page and widget settings would already help a great deal in finding the root cause.

I will check it and if a fix is needed do that next week.

I do know it should work in Mendix 8, so not sure what has changed in the version of Mendix 8 which you are using.

Regards,
Ivo

Op 15 aug. 2020 om 17:09 heeft Mark Mellink <notifications@github.com> het volgende geschreven:

﻿

Hi,

I can't load markers using Mendix 8.11. I get the following error message in the console:

obj.get is not a function TypeError: obj.get is not a function at S.<computed>.E.<anonymous> (http://localhost:8080/widgets/GoogleMapsCustomMarker/widget/GoogleMapsCustomMarker.js?637331078010923573:502:100) at http://localhost:8080/mxclientsystem/mxui/mxui.js?637331078010923573:5:27280 at Object.forEach (http://localhost:8080/mxclientsystem/mxui/mxui.js?637331078010923573:5:31063) at S.<computed>.E._refreshMap (http://localhost:8080/widgets/GoogleMapsCustomMarker/widget/GoogleMapsCustomMarker.js?637331078010923573:480:23) at S.<computed>.E.parseObjects (http://localhost:8080/widgets/GoogleMapsCustomMarker/widget/GoogleMapsCustomMarker.js?637331078010923573:684:9) at S.<computed>.E.<anonymous> (http://localhost:8080/widgets/GoogleMapsCustomMarker/widget/GoogleMapsCustomMarker.js?637331078010923573:584:12) at S.<computed>.E.<anonymous> (http://localhost:8080/mxclientsystem/mxui/mxui.js?637331078010923573:5:27280) at http://localhost:8080/mxclientsystem/mxui/mxui.js?637331078010923573:80:8288

**Comment by MarkMellink** [comment] 2020-08-16 09:20
Hi Ivo,

Sure, I've attached some pictures of the way I have it setup!

*In short what I'm trying to do: *I'm trying to load "trips" on a map. I've
been playing around with several widgets and so far have the normal Mendix
"Maps" widget working, but I'd prefer using yours as it has a little more
flexibility in the map options (e.g. starting out using Satellite).

*This is how the widget is loaded on the page:*

[image: image.png]
*This is the result with your widget:*
[image: image.png]

*This is the domain model of the two entities (Context entity + Entity I
try to load on the map):*
[image: image.png]
*This is the context entity creation microflow (simply creates a blank
object of the filter and returns it):*
[image: image.png]

*These are the settings of the data source:*
[image: image.png]
*This is the "RetrieveTrips" microflow:*
[image: image.png]
*This is the result of I use the standard Mendix "Maps" widget (2 trips
loaded so far):*
[image: image.png]


*I've attached screenshots of my other widget settings just in case, but I
figured the data source one was the most relevant:*
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]

Thanks for the quick response. Overall looks like a great widget and would
love to make use of it :)

Thanks,

Mark

**Comment by ivosturm** [comment] 2020-08-18 08:40
Hi Mark,

I just upgraded my test project to Mendix 8.11.1 and all features seem to work a expected. Not sure why I don;t see all the added details (page setup/widget settings) you added here. Can you send me an e-mail directly with these pictures of your page setup and widget settings?

ivo.sturm@firstconsulting.nl

**Comment by ivosturm** [comment] 2020-09-09 06:26
Hi Mark, I will close this issue as it wasn't an issue but related to your configuration.

**Closed as completed by ivosturm** 2020-09-09 06:26 UTC
