### ISSUE TITLE
Zoom level too high

### ISSUE THREAD

**Issue by ssuijkerbuijk** [ivosturm/GoogleMapsCustomMarker#16] opened 2018-11-06 12:43 UTC
I'm using the widget with a microflow as datasource in a mendix tab widget. When the widget is on the second tab (not the default one) the zoomlevel is way too high. When that tab is the default tab displayed on opening the page, everything looks fine. Any solution/workaround for this? Thanks.

**Comment by ivosturm** [comment] 2018-11-06 13:30
Hi,

This is actually a known issue of Google Maps in a tab container. See issue no. 10. This is not something I can solve without extreme customization, which is not preferred. The problem is that a non-active tab pane is not fully loaded and Google does not cope with that very well.

I will close this issue, since it is not something I can fix.

Kind regards,
Ivo


Van: ssuijkerbuijk <notifications@github.com>
Verzonden: dinsdag 6 november 2018 13:43
Aan: ivosturm/GoogleMapsCustomMarker <GoogleMapsCustomMarker@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ivosturm/GoogleMapsCustomMarker] Zoom level too high (#16)


I'm using the widget with a microflow as datasource in a mendix tab widget. When the widget is on the second tab (not the default one) the zoomlevel is way too high. When that tab is the default tab displayed on opening the page, everything looks fine. Any solution/workaround for this? Thanks.

**Comment by ssuijkerbuijk** [comment] 2018-11-06 13:43
Hi Ivo. Thanks for your explanation. Didn't see the other issue.

**Comment by ivosturm** [comment] 2019-01-12 10:47
As mentioned, I can't fix this scenario in a generic way.

**Closed as completed by ivosturm** 2019-01-12 10:47 UTC
