### ISSUE TITLE
Toggle dragging does not work

### ISSUE THREAD

**Issue by rcha103** [ivosturm/GoogleMapsCustomMarker#1] opened 2017-05-12 03:32 UTC
When the marker option Toggle dragging is enabled, the map does not load. Found out that the code
`var toggleMarkerNode = dom.input({ type : 'checkbox', 'class' : 'toggleCheckBox'});` does not get executed properly. A fix would be awesome! Thanks!

**Comment by ivosturm** [comment] 2017-05-12 05:53
Hi Rcha3,

Which version of Mendix do you use when this error occurs. In Mendix 6 I can't reproduce, so probably 7?

Let me know, thanks!

Regards,
Ivo

Op 12 mei 2017 om 05:32 heeft rcha103 <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


When the marker option Toggle dragging is enabled, the map does not load. Found out that the code
var toggleMarkerNode = dom.input({ type : 'checkbox', 'class' : 'toggleCheckBox'}); does not get executed properly. A fix would be awesome! Thanks!

**Comment by rcha103** [comment] 2017-05-12 06:06
Hi @ivosturm 
yes you are correct, I am using Mendix 7.2.0 to be specific.

**Comment by ivosturm** [comment] 2017-05-12 10:22
For Mendix 7 some changes have been done on the Client API. The change that is now breaking the widget is this one (see: https://docs.mendix.com/refguide7/moving-from-6-to-7):

·        mxui/dom.{p,div,span...} and mxui/dom.builder have been removed in favor of using mxui/dom.create

I will fix this on Monday, so the fix will be availabe in the AppStore next Wednesday I think.

Kind regards,
Ivo

Van: rcha103 [mailto:notifications@github.com]
Verzonden: vrijdag 12 mei 2017 8:07
Aan: ivosturm/GoogleMapsCustomMarker <GoogleMapsCustomMarker@noreply.github.com>
CC: Ivo Sturm <ivo.sturm@firstconsulting.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [ivosturm/GoogleMapsCustomMarker] Toggle dragging does not work (#1)


Hi @ivosturm<https://github.com/ivosturm>
yes you are correct, I am using Mendix 7.2.0 to be specific.

**Comment by worthingtonte** [comment] 2017-06-08 10:19
Hi @ivosturm 

I am also having the same issue with the toggle dragging not working. I am using 7.3.0.

Do you know roughly when a fix will be in the app store?

Thank you very much,

Tom

**Comment by ivosturm** [comment] 2017-06-10 02:22
Hi Tom,

I will fix this somewhere next week. I did not upgrade the code to Mendix 7 yet. The toggle dragging is definitely working in Mendix 6. Expect to have both working again at latest 16th of June in your mentioned Mendix version.

Hope it is fine!

Regards
Ivo

Op 8 jun. 2017 om 15:49 heeft worthingtonte <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi @ivosturm<https://github.com/ivosturm>

I am also having the same issue with the toggle dragging not working. I am using 7.3.0.

Do you know roughly when a fix will be in the app store?

Thank you very much,

Tom

**Comment by ivosturm** [comment] 2017-07-04 12:15
This issue should be fixed with the newest available release in the Mendix App Store. Feel free to rate the widget if it works!

**Closed as completed by ivosturm** 2017-07-04 12:15 UTC
